### ISSUE TITLE
Restructure to show progress more easily

### ISSUE THREAD

**Issue by kipprice** [Codecademy/engineering-competencies#11]
This is a hard document to parse if you're trying to understand what separates two levels, because there's a lot of duplicative expectations (since many of these are cumulative). It would be easier to understand what would take an individual to the next level if we structured into 
- Expected at all levels
- What's special about expectations at level {0-4}

**Comment by JoshuaKGoldberg** [comment]
Closing out this old issue as I'm guessing it's not remembered+relevant anymore. Cheers! ❤️
