### ISSUE TITLE
Competencies don't include "insightful" code reviews at SE 2 + 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Codecademy/engineering-competencies#6]
Providing timely code reviews is part of the engineering competencies at all non-intern levels, as well as generally providing feedback, but nothing about feedback in code reviews. I think it'd be a good idea to explicitly mention knowledge sharing in code reviews for engineer 2s and up.

Thoughts?

**Comment by oplattner** [comment]
agree, i think one way to add it would be to say something along the lines of "You start to provide feedback in code reviews" at the engineering x-level.

**Comment by JoshuaKGoldberg** [comment]
Closing out this old issue as I'm guessing it's not remembered+relevant anymore. Cheers! ❤️
